### ISSUE TITLE
doubt on usage

### ISSUE THREAD

**Issue by beckmx** [MatzElectronics/epilog-svg#1]
the file expects the selection of a previously created svg file, right?

**Comment by MatzElectronics** [comment]
Yes, here's a help doc - I didn't expect this to get found, but glad you're here!
[https://docs.google.com/document/d/1YmjPfB_6JlW0vhVOJKeXdoiSZluG9xtQmILkLeKg7mk/edit](https://docs.google.com/document/d/1YmjPfB_6JlW0vhVOJKeXdoiSZluG9xtQmILkLeKg7mk/edit)

**Comment by beckmx** [comment]
got it, looks like my fusion installation doesnt like shaper, it doesnt load in the menu :(

**Comment by MatzElectronics** [comment]
Try looking under the make menu in the tools bar:
![image](https://user-images.githubusercontent.com/19737272/69195827-a297d400-0ae1-11ea-8e13-adc9d1a90961.png)

I ended up having to uninstall and re-install fusion at one point because mine ad disappeared once, too.

**Comment by beckmx** [comment]
I raised an issue with the shaper guys, looks like an issue on their end, what fusion version do you have?

**Comment by MatzElectronics** [comment]
I'm currently using 2.0.6658
